volumes:
  libretranslate_data:

services:
  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      - LT_DISABLE_WEB_UI=true
#      - LT_REQ_LIMIT=300
#      - LT_DEBUG=1
#      - LT_DISABLE_FILESYSTEM_LOADING=false
#    volumes:
#      - ./libretranslate_data:/home/libretranslate/.local/share/argos-translate
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'grep -q \"Starting gunicorn\" /proc/1/fd/1 2>/dev/null || grep -q \"Starting gunicorn\" /proc/1/fd/2 2>/dev/null'"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: backend/.
    ports:
      - "8000:8000"
    environment:
      - LT_URL=http://libretranslate:5000
    depends_on:
      libretranslate:
        condition: service_healthy

  frontend:
    build:
      context: frontend/.
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_started
