version: "3.9"

services:
  libretranslate:
    hostname: libretranslate
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_DISABLE_WEB_UI=true

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LT_URL=http://libretranslate:5000
    depends_on:
      - libretranslate

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
